### PR TITLE
gst: add wrapper for deinit function

### PR DESCRIPTION
**Pull request by solganik**
Adding wrapper for deinit function.

### CODE REVIEW

**Comment by solganik** [comment]
@tinyzimmer  any idea why do i get the 
root@9728ad43effa:/workspace# go build examples/bins/main.go 
# github.com/tinyzimmer/go-gst/gst
cgo-gcc-prolog: In function '_cgo_d934d0bd99ce_Cfunc_gst_deinit':
cgo-gcc-prolog:66:49: warning: unused variable '_cgo_a' [-Wunused-variable]

**Comment by tinyzimmer** [comment]
> @tinyzimmer any idea why do i get the
> root@9728ad43effa:/workspace# go build examples/bins/main.go
> 
> # github.com/tinyzimmer/go-gst/gst
> cgo-gcc-prolog: In function '_cgo_d934d0bd99ce_Cfunc_gst_deinit':
> cgo-gcc-prolog:66:49: warning: unused variable '_cgo_a' [-Wunused-variable]

Not sure - can take a look later and see. What platform just out of curiosity?

**Comment by solganik** [comment]
On linux, inside the build docker

**Comment by tinyzimmer** [comment]
This could be due to the `-Wall` [here](https://github.com/tinyzimmer/go-gst/blob/main/gst/pkg_config.go#L5). Could you maybe try dropping that argument on this PR and see if it fixes the issue.

I found [this](https://stackoverflow.com/questions/56633817/warning-unused-variable-cgo-a) on StackOverflow that led me down that path. I'm just surprised it didn't pop up sooner.

**Comment by solganik** [comment]
yeah i saw this as well .. i removed the "unused warning"  in additional patch

**Comment by tinyzimmer** [comment]
LGTM

**Pull request merged**
